"""Phase 0 analytics: cycle time, churn metrics (plan §2 ``analytics/``).

Computations consume canonical issues/transitions only — no connector clients.
"""

from throughline.analytics.cycle_time import (
    CyclePass,
    CycleTimeResult,
    compute_and_store_outcomes_for_org,
    compute_cycle_time,
    store_outcome,
)
from throughline.analytics.reopen import (
    AggregateDimension,
    IssueDimensions,
    ReopenDetection,
    aggregate_detections,
    compute_and_store_reopens_for_org,
    detect_reopens,
    is_reopen_transition,
    rebuild_reopen_aggregates,
    store_reopen_detections,
)
from throughline.analytics.scope_change import (
    EpicChild,
    EpicScopeResult,
    LateChildDetection,
    SpecChangeDetection,
    SpecField,
    aggregate_scope_signals,
    compute_and_store_scope_change_for_org,
    detect_late_children,
    detect_spec_changes,
    epic_started_at,
    first_in_progress_at,
    measure_epic_scope,
    rebuild_scope_change_aggregates,
    store_late_child_detections,
    store_spec_change_detections,
)
from throughline.analytics.spec_quality import (
    COMMENT_IMPORT_DEPENDENCY_ISSUE,
    COMMENT_TRAFFIC_STATUS_UNAVAILABLE,
    SHORT_DESCRIPTION_MAX_CHARS,
    AcCoverage,
    DescriptionLengthBucket,
    SpecQualityAggregateRow,
    SpecQualityDimension,
    SpecQualityIssueDetection,
    ac_coverage_for_issue,
    aggregate_spec_quality,
    comment_traffic_indicator,
    compute_and_store_spec_quality_for_org,
    description_length_bucket,
    description_length_chars,
    detect_spec_quality_for_issue,
    org_has_ac_field_mapping,
    rebuild_spec_quality_aggregates,
    store_spec_quality_indicators,
)
from throughline.analytics.status import StatusLane, classify_status, status_map_classifier

__all__ = [
    "COMMENT_IMPORT_DEPENDENCY_ISSUE",
    "COMMENT_TRAFFIC_STATUS_UNAVAILABLE",
    "SHORT_DESCRIPTION_MAX_CHARS",
    "AcCoverage",
    "AggregateDimension",
    "CyclePass",
    "CycleTimeResult",
    "DescriptionLengthBucket",
    "EpicChild",
    "EpicScopeResult",
    "IssueDimensions",
    "LateChildDetection",
    "ReopenDetection",
    "SpecChangeDetection",
    "SpecField",
    "SpecQualityAggregateRow",
    "SpecQualityDimension",
    "SpecQualityIssueDetection",
    "StatusLane",
    "ac_coverage_for_issue",
    "aggregate_detections",
    "aggregate_scope_signals",
    "aggregate_spec_quality",
    "classify_status",
    "comment_traffic_indicator",
    "compute_and_store_outcomes_for_org",
    "compute_and_store_reopens_for_org",
    "compute_and_store_scope_change_for_org",
    "compute_and_store_spec_quality_for_org",
    "compute_cycle_time",
    "description_length_bucket",
    "description_length_chars",
    "detect_late_children",
    "detect_reopens",
    "detect_spec_changes",
    "detect_spec_quality_for_issue",
    "epic_started_at",
    "first_in_progress_at",
    "is_reopen_transition",
    "measure_epic_scope",
    "org_has_ac_field_mapping",
    "rebuild_reopen_aggregates",
    "rebuild_scope_change_aggregates",
    "rebuild_spec_quality_aggregates",
    "status_map_classifier",
    "store_late_child_detections",
    "store_outcome",
    "store_reopen_detections",
    "store_spec_change_detections",
    "store_spec_quality_indicators",
]
